### ISSUE TITLE
我用goland打开代码运行时出现这个问题

### ISSUE THREAD

**Issue by AeolianChimes** [zhangyu0310/wechat-setu-bot#2]
![~DP0O2TMVOJG5SL2OP}C%RJ](https://user-images.githubusercontent.com/89448385/130610139-077efdc5-ef99-4bf2-b90a-15eb8975629c.png)
我还需要做些什么，运行后没有找到可以输入Webhook地址的地方，下午是第一次接触go代码，有这些不懂的地方

**Comment by poppinzhang** [comment]
如果只是想运行项目，可以直接下载我编译好的发布版本。在Git项目release中，会有Windows平台和Linux CentOS的二进制文件。

建议去找个Go的入门教程，从图片看，这个GoLand项目没有指定GOROOT路径，GoLand找不到对应的Go语言编译器。

**Comment by AeolianChimes** [comment]
![企业微信截图_16298746697930](https://user-images.githubusercontent.com/89448385/130741577-0e5bc898-ac13-458d-b22d-41aee81151b3.png)
感谢你的耐心指导，我已经成功实现了，只是在cmd保持启动才能执行，有没有一种办法可以关闭后台也可以保持推送着

**Comment by poppinzhang** [comment]
Windows 想让程序后台运行需要注册为服务，网上有教程，有些繁琐，因为不属于程序本身的问题，所以没有考虑去做。

Linux下直接执行命令，末尾加 & 即可后台运行。
