### ISSUE TITLE
想提两个建议

### ISSUE THREAD

**Issue by guohuiyuan** [zhangyu0310/wechat-setu-bot#5]
1. 作者有考虑把企业微信webhook发消息和发图片拆成两个项目吗
2. 可能不需要图片代理服务器，把"i.pixiv.cat"替换成"i.pixiv.re"，就可以直接访问图片

**Comment by poppinzhang** [comment]
拆开是为了只推送图片吗？做应该可以做，加个参数就能解决。
我理解这个cat和re，应该都得pixiv的图片代理吧。pixiv官方应该是禁止外链的。
